# Generated by Django 5.0.1 on 2024-01-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_bloco_colaborador_bloco_data_bloco_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma',
            name='colaborador',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
