# Generated by Django 5.0.1 on 2024-01-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_forma_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma',
            name='calcanhar',
            field=models.CharField(default=900, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forma',
            name='ombro',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forma',
            name='pescoco',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
