# Generated by Django 5.0.1 on 2024-01-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_forma_calcanhar_forma_ombro_forma_pescoco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloco',
            old_name='encaixe_ffo',
            new_name='encaixe_angular',
        ),
        migrations.RenameField(
            model_name='bloco',
            old_name='furo_de_escape',
            new_name='encaixe_fb',
        ),
    ]
