# Generated by Django 5.0.1 on 2024-02-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_encaixe_ffo_bloco_encaixe_angular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='hora',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coroa',
            name='hora',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forma',
            name='hora',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
