# Generated by Django 5.0.1 on 2024-02-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_bloco_hora_coroa_hora_forma_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloco',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='coroa',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='forma',
            name='hora',
        ),
    ]
